"use client"
import Link from "next/link"
import { usePathname } from "next/navigation"
import { useState } from "react"



// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }



const navLine = [
  { name: "Login", href: "/login" },
  { name: "Register", href: "/register" },
  { name: "Forgot Password", href: "/forgot-password" },
]


export default function AuthRootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathName = usePathname()

  const [input, setInput] = useState("")
  return (
    <html lang="en">
      <body>
        <header className="p-5">

<div>
  <input value={input} onChange={(e) => setInput(e.target.value)} />
</div>
          <ul>
            {
              navLine.map((nav) => {
               const isActive = pathName === nav.href || (pathName.startsWith(nav.href) && nav.href !== "/");
                return (
               
                  <Link href={nav.href} key={nav.name}>
                  <span className={isActive ? "font-bold mr-4" : "text-blue-500 mr-4"}>
                    {nav.name}
                  </span>
                </Link>
                
                )
              })
            }
          </ul>
        </header>
        {children}

        <footer className="text-red-500">
          <h1> Auth Footer</h1>
        </footer>
      </body>
    </html>
  )
}
