export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function MarketingRootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor:"rgb(174, 172, 172)"}}>
          <h1>marketing Header</h1>
        </header>
        {children}
        
        <footer style={{backgroundColor: "rgb(174, 172, 172)"}}>
          <h1>Footer</h1>
        </footer>
        </body>
    </html>
  )
}
